/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.ResultSet;
import com.mysql.jdbc.Statement;
import com.toedter.calendar.JCalendar;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.sl.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Gmurillo
 */
public class Informe extends javax.swing.JFrame {
    
    private String buscar = "";

    Menu Menu;
    Sesion Sesion;
    
    String pantalla;
    String factura;
    
    //Variable que contiene la fecha actual
    LocalDate FechaActual = LocalDate.now();
    DateTimeFormatter formatoPersonalizadoExcel = DateTimeFormatter.ofPattern("d-M-yyyy");
    String Fecha_Actual_Excel = FechaActual.format(formatoPersonalizadoExcel);
        
    DateTimeFormatter formatoPersonalizado = DateTimeFormatter.ofPattern("d/M/yyyy");
    String Fecha_Actual_Formateada = FechaActual.format(formatoPersonalizado);
    
    /**
     * Creates new form tet--
     */
    public Informe() {
        initComponents();
        facturasee();
        System.out.println("Por Entregar");
        this.setLocationRelativeTo(null);
        //this.setResizable(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Logo_Atlas.png")));
    }
    
    public void buscar_factura(String busca){   
        buscar = busca;
        facturasee();
    }
    
    public void Pantallas(String pantalla){
        this.pantalla = pantalla;
    }
      
    String consulta;
    String factu;
    String consulta_movi;
    String consulta_Excel;
    String consulta_insertar;
    
    public void facturasee(){
        //Factura.setText(null);
        Cuenta.setText(null);
        Nombre.setText(null);
        //Fiscal.setText(null);
        //Monto.setText(null);
        Transaccion.setText(null);
        //Observacion_text_big.setText( null);
        Estado.setSelectedItem(null);
        Fecha.setDate(null);
        
        DefaultTableModel modelo= (DefaultTableModel) table_factura.getModel();
        modelo.setRowCount(0);  
    try{
        Connection con = (Connection) ConexionMySQL.obtenerConexion();
        Statement stat = (Statement) con.createStatement();
            
        if(buscar.isEmpty()){
            consulta = "Select * From facturas";
        }
        else if (!buscar.isEmpty()){
            consulta = "Select * From facturas WHERE facturas.InvoiceNumber LIKE '%" + buscar + "%' OR facturas.DeptorNumber LIKE '%" + buscar + "%' OR facturas.cmp_name LIKE '%" + buscar + "%'";
        }
        
        ResultSet rs = (ResultSet) stat.executeQuery(consulta);
        
        rs.first();
        
        do{ 
            String[] fila = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(5)};
                modelo.addRow(fila);
        }while(rs.next());
    }
    catch(ClassNotFoundException | SQLException ex){
        java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Cuenta_text = new javax.swing.JLabel();
        Cuenta = new javax.swing.JTextField();
        Nombre_text = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Transaccion_text = new javax.swing.JLabel();
        Transaccion = new javax.swing.JTextField();
        Estado_text = new javax.swing.JLabel();
        Estado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_factura = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        Buscar_text = new javax.swing.JLabel();
        Buscar = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Enviar_button = new javax.swing.JButton();
        Fecha = new com.toedter.calendar.JDateChooser();
        Fecha_text = new javax.swing.JLabel();
        Fecha_text1 = new javax.swing.JLabel();
        Fecha1 = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1002, 464));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1002, 464));

        jPanel3.setBackground(new java.awt.Color(0, 40, 87));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantallas/Logo_Atlas.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 215, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INFORME");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Regresar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Regresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(244, 244, 244));

        Cuenta_text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cuenta_text.setText("Cuenta");

        Cuenta.setBackground(new java.awt.Color(242, 242, 242));
        Cuenta.setEnabled(false);
        Cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaActionPerformed(evt);
            }
        });

        Nombre_text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Nombre_text.setText("Nombre");

        Nombre.setBackground(new java.awt.Color(242, 242, 242));
        Nombre.setAutoscrolls(false);
        Nombre.setEnabled(false);

        Transaccion_text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Transaccion_text.setText("Transacción");

        Transaccion.setEnabled(false);

        Estado_text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Estado_text.setText("Estado");

        Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por entregar", "En ruta", "Entregado", "Multa", "Sin información", "No encontrado" }));
        Estado.setEnabled(false);
        Estado.setFocusable(false);

        table_factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N° De Factura", "N° De Cuenta", "Nombre", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_factura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_facturaMousePressed(evt);
            }
        });
        table_factura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_facturaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table_factura);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Transaccion_text)
                        .addGap(6, 6, 6)
                        .addComponent(Transaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Nombre_text)
                        .addGap(27, 27, 27)
                        .addComponent(Cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Estado_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cuenta_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cuenta_text)
                            .addComponent(Nombre_text)
                            .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Transaccion_text)
                            .addComponent(Transaccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Estado_text)
                            .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(244, 244, 244));

        Buscar_text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Buscar_text.setText("Buscar");

        Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscarKeyReleased(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("Actualizar lista");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Buscar_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar_text))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Enviar_button.setText("Descargar informe");
        Enviar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enviar_buttonActionPerformed(evt);
            }
        });

        Fecha.setToolTipText("22/10/2023");
        Fecha.setDateFormatString("d/M/yyyy");

        Fecha_text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Fecha_text.setText("Desde");

        Fecha_text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Fecha_text1.setText("Hasta");

        Fecha1.setToolTipText("22/10/2023");
        Fecha1.setDateFormatString("d/M/yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Fecha_text)
                .addGap(18, 18, 18)
                .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(Fecha_text1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Enviar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Fecha_text)
                        .addComponent(Fecha_text1))
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(Enviar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 40, 87));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String fecha_excel = "";
    String fecha_excel_formateada = "";
    int cantidad;
    
    public void crearExcel(String fecha_excel, String fecha_excel_formateada) throws FileNotFoundException, IOException {
        this.fecha_excel = fecha_excel;
        this.Fecha_Actual_Formateada = fecha_excel_formateada;
        
        String ExcelFileName = fecha_excel+".xlsx";
        File ExcelFile = new File(ExcelFileName);
                    
        boolean validacion_excel = ExcelFile.exists();
      
        Workbook book;
        
        if(!validacion_excel){
            book = new XSSFWorkbook();
            org.apache.poi.ss.usermodel.Sheet sheet = book.createSheet("Movimientos");
            
            sheet.setColumnWidth(0, 4000);
            sheet.setColumnWidth(1, 4000); 
            sheet.setColumnWidth(2, 8000);  
            sheet.setColumnWidth(3, 10000);  
            sheet.setColumnWidth(4, 4000);  
            sheet.setColumnWidth(5, 4000);  
            sheet.setColumnWidth(6, 10000);  
            sheet.setColumnWidth(7, 5000);  
            sheet.setColumnWidth(8, 4000);  
            sheet.setColumnWidth(9, 5000);  
            sheet.setColumnWidth(10, 4000);
            sheet.setColumnWidth(11, 4000);
           
            Row rowuno = sheet.createRow(0);
            rowuno.createCell(0).setCellValue("InvoiceNumber");
            rowuno.createCell(1).setCellValue("DeptorNumber");
            rowuno.createCell(2).setCellValue("cmp_name");
            rowuno.createCell(3).setCellValue("Descripcion");
            rowuno.createCell(4).setCellValue("AmountTC");
            rowuno.createCell(5).setCellValue("Transaccion");
            rowuno.createCell(6).setCellValue("Observacion");
            rowuno.createCell(7).setCellValue("Estatus");
            rowuno.createCell(8).setCellValue("Date");
            rowuno.createCell(9).setCellValue("Seccion");
            rowuno.createCell(10).setCellValue("DueDate");
            rowuno.createCell(11).setCellValue("Fechas");
        }
        
        else{
            FileInputStream fileInput = new FileInputStream(ExcelFile);       
            book = new XSSFWorkbook(fileInput);
        }
        
        org.apache.poi.ss.usermodel.Sheet sheet = book.getSheet("Movimientos");
        
        String password = "12345";
        sheet.protectSheet(password);
        
        try{
            Connection con = (Connection) ConexionMySQL.obtenerConexion();
            Statement stat = (Statement) con.createStatement();
                    
            consulta_Excel= "Select * From movimientos WHERE fecha LIKE '%" + fecha_excel_formateada + "%'";

            ResultSet ce = (ResultSet) stat.executeQuery(consulta_Excel);

            ce.first();

            do{ 
                cantidad = ce.getInt(3);
                System.out.println(cantidad);
            }
            while(ce.next());
        }
            catch(ClassNotFoundException | SQLException ex){
                java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }         
        
        try{
            Connection con = (Connection) ConexionMySQL.obtenerConexion();
            Statement stat = (Statement) con.createStatement();
                    
            //consulta_insertar= "Select * FROM ruta WHERE InvoiceNumber LIKE '%" + Factura.getText() + "%'";

            ResultSet ci = (ResultSet) stat.executeQuery(consulta_insertar);

            ci.first();

            do{ 
                Row row = sheet.createRow(cantidad);
                for(int i=0; i<12; i++){
                    row.createCell(i).setCellValue(ci.getString(i+1));
                    //row.createCell(3).setCellFormula("1+3");
                }
            }
            while(ci.next());
        }
            catch(ClassNotFoundException | SQLException ex){
                java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        try {
            FileOutputStream fileout = new FileOutputStream(ExcelFileName);
            book.write(fileout);
            fileout.close();
        } catch (FileNotFoundException ex) {
        } catch (IOException ex) {
        }
        /*
            String password = "12345";

            sheet.protectSheet(password);

            Row row = sheet.createRow(0);
            row.createCell(0).setCellValue("1");
            row.createCell(1).setCellValue("2");
            row.createCell(2).setCellValue("3");

            Cell celda = row.createCell(3);
            celda.setCellFormula(String.format("1+3", ""));

            Row rowuno = sheet.createRow(1);
            rowuno.createCell(0).setCellValue(7);
            rowuno.createCell(1).setCellValue(8);

            Cell celdauno = rowuno.createCell(2);
            celdauno.setCellFormula(String.format("A%d+B%d", 2, 2));

            try {
                FileOutputStream fileout = new FileOutputStream(fecha_excel+".xlsX");
                book.write(fileout);
                fileout.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Por_entregar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Por_entregar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
 
            Workbook book = new XSSFWorkbook();
            try{
                Connection con = (Connection) ConexionMySQL.obtenerConexion();
                Statement stat = (Statement) con.createStatement();

                consulta_Excel= "Select * From movimientos WHERE fecha LIKE '%" + fecha_excel_formateada + "%'";

                ResultSet ce = (ResultSet) stat.executeQuery(consulta_Excel);

                ce.first();

                do{ 
                    cantidad = ce.getInt(3);
                    System.out.print(cantidad);
                }while(ce.next());
            }
            catch(ClassNotFoundException | SQLException ex){
                java.util.logging.Logger.getLogger(Por_entregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            
            Row row = sheet.createRow(0);
            for (int i = 0; i<cantidad; i++){
            row.createCell(0).setCellValue(i);
            row.createCell(1).setCellValue(i);
            row.createCell(2).setCellValue(cantidad);
            }
        }
        */
    }

    public void leerExcel() {
        try {
            FileInputStream file = new FileInputStream(new File(Fecha_Actual_Excel+".xlsx"));

            XSSFWorkbook wb = new XSSFWorkbook(file);
            XSSFSheet sheet = wb.getSheetAt(0);

            int numFilas = sheet.getLastRowNum();

            for (int a = 0; a <= numFilas; a++) {
                Row fila = sheet.getRow(a);
                int numCols = fila.getLastCellNum();

                for (int b = 0; b < numCols; b++) {
                    Cell celda = fila.getCell(b);

                    switch (celda.getCellTypeEnum().toString()) {
                        case "NUMERIC":
                            System.out.print(celda.getNumericCellValue() + " ");
                            break;

                        case "STRING":
                            System.out.print(celda.getStringCellValue() + " ");
                            break;

                        case "FORMULA":
                            System.out.print(celda.getCellFormula() + " ");
                            break;
                    }
                }
                System.out.println("");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Informe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Informe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void modificarExcel(String fecha_excel, String fecha_excel_formateada) {
        this.fecha_excel = fecha_excel;
        this.fecha_excel_formateada = fecha_excel_formateada;
        try {
            FileInputStream file = new FileInputStream(new File(fecha_excel+".xlsX"));

            XSSFWorkbook wb = new XSSFWorkbook(file);
            XSSFSheet sheet = wb.getSheetAt(0);

            String password = "12345";

            sheet.protectSheet(password);

            XSSFRow fila = sheet.getRow(0);

            if (fila == null) {
                fila = sheet.createRow(0);
            }

            XSSFCell celda = fila.createCell(0);

            if (celda == null) {
                celda = fila.createCell(0);
            }

            celda.setCellValue("Modificacionnumero2");

            file.close();

            FileOutputStream output = new FileOutputStream("Excel1.xlsX");
            wb.write(output);
            output.close();
        } catch (IOException ex) {
            Logger.getLogger(Informe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        if("admin".equals(this.pantalla)){
            Menu menu = new Menu();
            menu.setVisible(true);
            this.setVisible(false);
        }
        else if ("entregar".equals(this.pantalla)){
            Sesion sesion = new Sesion();
            sesion.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_RegresarActionPerformed

    private void Enviar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enviar_buttonActionPerformed
        // TODO add your handling code here:
        
        //Obtiene la fila que fue seleccionada por el usuario
        int lista = table_factura.getSelectedRow();
        String fa = table_factura.getValueAt(lista, 0).toString();
        
        //Otorgamos la fecha del formulario a una variable para validarla mas adelante
        Date fecha = Fecha.getDate();
        
        DefaultTableModel modelo= (DefaultTableModel) table_factura.getModel();
        modelo.setRowCount(0);  
        try{
            //Conexión a la base de datos
            Connection con = (Connection) ConexionMySQL.obtenerConexion();
            Statement stat = (Statement) con.createStatement();

                //Validacion en caso de que el usuario no ingrese una fecha
              
                    //Consulta para validar si existe algun elemento que contenga la fecha actual
                    consulta_movi = "Select * FROM movimientos WHERE fecha = '"+Fecha_Actual_Formateada+"'";
                    ResultSet fe = (ResultSet) stat.executeQuery(consulta_movi);
                    
                    //variable de tipo booleano que guarde el estado de la validacion
                    boolean validacion_movimientos = fe.next();
                    
                    //System.out.println("Confirmacion movimientos: "+validacion_movimientos);
                    //System.out.println("Confirmacion Excel: "+validacion_excel);
                    
                    //Accion en caso de que si exista un elemento en la tabla "movimientos" con la fecha actual y tambien que exista un excel con la fecha actual
                    if(validacion_movimientos){
                        System.out.println("Ambos existen");
                        consulta_movi =  """
                                UPDATE movimientos
                                SET cantidad = cantidad + 1
                                WHERE fecha = '%s'
                            """.formatted(Fecha_Actual_Formateada);
                        
                        int filas_movimientos = stat.executeUpdate(consulta_movi);
                        crearExcel(Fecha_Actual_Excel, Fecha_Actual_Formateada);
                    }
                    //Accion en caso de que no exista ni un elemento en la tabla "movimientos" ni el excel con la fecha actual
                    else{
                        System.out.println("Ninguno existe");
                        consulta_movi =  """
                              INSERT INTO movimientos (fecha, cantidad)
                              SELECT '%s' AS fecha, '%s' AS cantidad;
                          """.formatted(Fecha_Actual_Formateada, 1);
                        
                              int filas_movimientos = stat.executeUpdate(consulta_movi);
                        crearExcel(Fecha_Actual_Excel, Fecha_Actual_Formateada);
                        System.out.println("Guardado");
                    }
                    //Vuelve a vaciar los elementos en la pantalla
                    facturasee();
                    JOptionPane.showMessageDialog(null, "La factura fue enviada exitosamente a la ruta.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                }     
        
        catch(ClassNotFoundException | SQLException | IOException ex){
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Enviar_buttonActionPerformed

    private void BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarKeyReleased
        // TODO add your handling code here:
        String nuevobuscar = Buscar.getText();
        this.buscar_factura(nuevobuscar);
    }//GEN-LAST:event_BuscarKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        facturasee();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void table_facturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_facturaKeyReleased
        // TODO add your handling code here:
        int lista = table_factura.getSelectedRow();
        String fa = table_factura.getValueAt(lista, 0).toString();
        
        try{
            Connection con = (Connection) ConexionMySQL.obtenerConexion();
            Statement stat = (Statement) con.createStatement();

            consulta = "Select * From facturas WHERE facturas.InvoiceNumber LIKE '%" + fa + "%'";

            ResultSet rs = (ResultSet) stat.executeQuery(consulta);

            rs.first();

            //Factura.setText(rs.getString(1));
            //Factura.setCaretPosition(0);
            Cuenta.setText(rs.getString(2));
            Cuenta.setCaretPosition(0);
            Nombre.setText(rs.getString(3));
            Nombre.setCaretPosition(0);
            //Fiscal.setText(rs.getString(4));
            //Fiscal.setCaretPosition(0);
            //Monto.setText(rs.getString(5));
            //Monto.setCaretPosition(0);
            Transaccion.setText(rs.getString(6));
            Transaccion.setCaretPosition(0);
            //Observacion_text_big.setText(rs.getString(7));
            //Observacion_text_big.setCaretPosition(0);
            if ("Por entregar".equals(rs.getString(8))){
                Estado.setSelectedIndex(0);
            }
            else if ("En ruta".equals(rs.getString(8))){
                Estado.setSelectedIndex(1);
            }
            else if ("Entregado".equals(rs.getString(8))){
                Estado.setSelectedIndex(2);
            }
            else if ("Multa".equals(rs.getString(8)) || "multa".equals(rs.getString(8)) || "MULTA".equals(rs.getString(8))){
                Estado.setSelectedIndex(3);
            }
            else if ("Sin informacion".equals(rs.getString(8))){
                Estado.setSelectedIndex(4);
            }
            else{
                Estado.setSelectedIndex(5);
            }
           // Estado.setCaretPosition(0);
            //Fecha.setDate(rs.getString(9));
            //Fecha.setCaretPosition(0);
        }
        catch(ClassNotFoundException | SQLException ex){
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_table_facturaKeyReleased

    private void table_facturaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_facturaMousePressed
        // TODO add your handling code here:
        int lista = table_factura.getSelectedRow();
        String fa = table_factura.getValueAt(lista, 0).toString();
        
        try{
            Connection con = (Connection) ConexionMySQL.obtenerConexion();
            Statement stat = (Statement) con.createStatement();

            consulta = "Select * From facturas WHERE facturas.InvoiceNumber LIKE '%" + fa + "%'";

            ResultSet rs = (ResultSet) stat.executeQuery(consulta);

            rs.first();

            //Factura.setText(rs.getString(1));
            //Factura.setCaretPosition(0);
            Cuenta.setText(rs.getString(2));
            Cuenta.setCaretPosition(0);
            Nombre.setText(rs.getString(3));
            Nombre.setCaretPosition(0);
            //Fiscal.setText(rs.getString(4));
            //Fiscal.setCaretPosition(0);
            //Monto.setText(rs.getString(5));
            //Monto.setCaretPosition(0);
            Transaccion.setText(rs.getString(6));
            Transaccion.setCaretPosition(0);
            //Observacion_text_big.setText(rs.getString(7));
            //Observacion_text_big.setCaretPosition(0);
            if ("Por entregar".equals(rs.getString(8))){
                Estado.setSelectedIndex(0);
            }
            else if ("En ruta".equals(rs.getString(8))){
                Estado.setSelectedIndex(1);
            }
            else if ("Entregado".equals(rs.getString(8))){
                Estado.setSelectedIndex(2);
            }
            else if ("Multa".equals(rs.getString(8)) || "multa".equals(rs.getString(8)) || "MULTA".equals(rs.getString(8))){
                Estado.setSelectedIndex(3);
            }
            else if ("Sin informacion".equals(rs.getString(8))){
                Estado.setSelectedIndex(4);
            }
            else{
                Estado.setSelectedIndex(5);
            }
           // Estado.setCaretPosition(0);
            //Fecha.setDate(rs.getString(9));
            //Fecha.setCaretPosition(0);
        }
        catch(ClassNotFoundException | SQLException ex){
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_table_facturaMousePressed

    private void CuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscar;
    private javax.swing.JLabel Buscar_text;
    private javax.swing.JTextField Cuenta;
    private javax.swing.JLabel Cuenta_text;
    private javax.swing.JButton Enviar_button;
    private javax.swing.JComboBox<String> Estado;
    private javax.swing.JLabel Estado_text;
    private com.toedter.calendar.JDateChooser Fecha;
    private com.toedter.calendar.JDateChooser Fecha1;
    private javax.swing.JLabel Fecha_text;
    private javax.swing.JLabel Fecha_text1;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel Nombre_text;
    private javax.swing.JButton Regresar;
    private javax.swing.JTextField Transaccion;
    private javax.swing.JLabel Transaccion_text;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_factura;
    // End of variables declaration//GEN-END:variables
}
